- name: Declare a variable at play level
  hosts: all
  connection: local
  vars:
    URL: dimpul.playbook.com
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}