- name: Demo on loops
  hosts: all
  connection: local
  tasks:
    - name: print fruit name
      debug:
        msg: fruit name is {{ item }}
      loop:
        - apple
        - jackfruit
    - name: print fruit name & quantity
      debug:
        msg: fruit name is {{ item.name }},quantity is {{ item.qty }}
      loop:
        - {name: "orange", qty: 100}
        - {name: "mango", qty: 200}