- name: Demo on condition
  hosts: all
  connection: local
  vars:
    a: 20
    b: true
  tasks:
    - name: string con
      debug:
       msg: print fruit name
      when: fruit_name == "apple"
    - name: num con
      debug:
        msg: a is greater than 10
      when: a > 10
    - name: boolean con
      debug:
        msg: b is true
      when: b